apiVersion: k8s.nginx.org/v1alpha1
kind: Policy 
metadata:
  name: dryrun-rate-limit-policy
spec:
  rateLimit:
    dryRun: true
    rate: 1r/s
    key: ${binary_remote_addr}
    zoneSize: 10M
    rejectCode: 503
