---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: restapi-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: restapi
  template: 
    metadata:
      labels:
        app: restapi
    spec:
      containers:
      - name: rest
        image: giriraj789/restapi:all
        ports:
        - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: user-svc
spec:
  selector:
    app: restapi
  ports:
    - protocol: TCP
      port: 8081
      targetPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: product-svc
spec:
  selector:
    app: restapi
  ports:
    - protocol: TCP
      port: 8082
      targetPort: 80
