apiVersion: k8s.nginx.org/v1
kind: VirtualServer
metadata:
  name: ht
spec:
  http-snippets: |
    underscores_in_headers on;
  host: ht.192.168.1.80.nip.io
  upstreams:
  - name: ht
    service: ht-svc
    port: 8090
  routes:
  - path: /
    action:
      pass: ht
