---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: dbbackend
  labels:
    app: db
spec:
  replicas: 1
  selector:
    matchLabels:
      app: db
  template:
    metadata:
      labels:
        app: db
    spec:
      containers:
      - name: mysql
        image: giriraj789/dball:v1 
        env:
        - name: MYSQL_ROOT_PASSWORD
          value: "root@123"
        ports:
        - containerPort: 3306
---
kind: Service
apiVersion: v1
metadata:
  name: dbbackend-svc
spec:
  selector:
    app: db
  ports:
  - protocol: TCP
    port: 3306
    targetPort: 3306
