apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: rest-ingress
spec:
  rules:
  - host: rest.192.168.1.81.nip.io
    http:
      paths:
      - path: /api/v1/users
        backend:
          serviceName: restapi-svc
          servicePort: 80
