---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: cafe
spec:
  replicas: 1
  selector:
    matchLabels:
      app: cafe
  template: 
    metadata:
      labels:
        app: cafe
    spec:
      containers:
      - name: cafe
        image: giriraj789/cafe:v1
        ports:
        - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: tea-svc
spec:
  selector:
    app: cafe
  ports:
    - protocol: TCP
      port: 8081
      targetPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: coffee-svc
spec:
  selector:
    app: cafe
  ports:
    - protocol: TCP
      port: 8082
      targetPort: 80
