apiVersion: k8s.nginx.org/v1
kind: VirtualServer
metadata:
  name: hdisci
  namespace: hdis
spec:
  host: hdisci.192.168.1.80.nip.io
  policies: 
  - name: rate-limit-policy
  - name: ip-allow-denyall-policy
  upstreams:
  - name: hd-ci
    service: hdis-svc-ci
    port: 80
  routes:
  - path: /
    action:
      pass: hd-ci
  
